### ISSUE TITLE
[ERR!] Error: unexpected status code: 401 on: https://api.github.com/repos/Asana/DefinitelyTyped/branches/master

### ISSUE THREAD

**Issue by ComLock** [Asana/typescript-starter#30]
Unable to install type defenitions.

(64bit arch linux, shouldn't matter though?)

**Comment by vsiao** [comment]
@pspeter3, I assume this repo is deprecated?

**Comment by pspeter3** [comment]
Yeah, we should put together a new one. I'm sorry @ComLock that this was misleading.

**Comment by bitjson** [comment]
@ComLock, @pspeter3, @vsiao: I've been working on an updated starter project here:

### [typescript-starter &rarr;](https://github.com/bitjson/typescript-starter)

Includes testing with code coverage, builds for Node.js and the browser, API documentation generation, and some other convenient tooling. Hope you find it useful!

**Comment by pspeter3** [comment]
That looks really well done!
